### ISSUE TITLE
exposing `bufnr` to be able to call `callback` programatically

### ISSUE THREAD

**Issue by beardedsakimonkey** [gpanders/fennel-repl.nvim#1]
Hi, I wanted a way to evaluate a form in a fennel buffer and have it execute in the fennel-repl buffer. In order to achieve this, I needed the repl buffer's `bufnr` to pass to `callback()`. (https://github.com/beardedsakimonkey/fennel-repl.nvim/commit/1b79d197c70051facac1cd84381890132a054776)

For context, this is how I implemented this functionality; not sure if there's a better way.
https://github.com/beardedsakimonkey/dotfiles/blob/86b70b5df9b504951313cdca87cbca3354816ed1/.config/nvim/after/ftplugin/fennel.fnl#L29-L37

Is this something you think should be exposed?  If so, I can make a PR.

Thanks

**Comment by gpanders** [comment]
Would returning `bufnr` from `start()` work for your purposes (I haven't looked closely at your code). I would prefer that over adding a new special purpose method.

**Comment by beardedsakimonkey** [comment]
That works, but calling `start()` also resets the environment such that variables that you had previously defined are no longer defined, which means every time I evaluate something from a fennel buffer, it wipes all the locals.
However, if I make this code run only when state.bufnr was previously nil (indicating a brand new repl session is being started)
https://github.com/gpanders/fennel-repl.nvim/blob/master/fnl/fennel-repl.fnl#L106-L120
then calling start unconditionally when evaluating something from a fennel buffer is no problem.
